services:
  db:
    image: mysql:8.1.0
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - db-volume:/var/lib/mysql
    ports:
      - 3306:3306

  api:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./backend:/myapp
    ports:
      - 3001:3000
    tty: true
    stdin_open: true
    depends_on:
      - db

  front:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    volumes:
      - ./frontend/app:/usr/src/app
    command: sh -c "npm i && npm start"
    ports:
      - 3000:3000
    tty: true
    stdin_open: true

volumes:
  db-volume:
