name: Check the source code
on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install packages
        run: |
          cd frontend/app
          npm ci
      - name: Run Prettier
        run: |
          cd frontend/app
          npm run format
      - name: Run ESLint
        run: |
          cd frontend/app
          npm run lint
